services:
  database:
    image: mysql
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      # Database configuration environment variables
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      # Database port (3307)
      - "3307:3306" 

  webserver:
    build: ./src
    volumes:
      - ./src:/app
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    command: supervisor -e '.' index.js
    environment:
      # Database configuration environment variables
      - DATABASE_HOST=${DATABASE_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SESSION_SECRET=${SESSION_SECRET}
      # Gmail configuration environment variables
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    # Server configuration environment variables
    ports:
      - "3000:3000"
